terraform_aks_rg_name = "terraform_rg"
terraform_aks_rg_location = "West Europe"
terraform_aks_name = "terraform-aks1"
terraform_aks_dns_prefix = "terraformaks1"
terraform_aks_node_size = "Standard_D2_v2"